function [BW,maskedImage] = segmentImage2(im)
%segmentImage segments image using auto-generated code from imageSegmenter App
%  [BW,MASKEDIMAGE] = segmentImage(IM) segments image IM using auto-generated
%  code from the imageSegmenter App. The final segmentation is returned in
%  BW and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 21-Jan-2016
%----------------------------------------------------


% Initialize segmentation with Otsu's threshold
level = graythresh(im);
mask = im2bw(im,level);

% Evolve segmentation
BW = activecontour(im, mask, 100, 'Chan-Vese');

% Form masked image from input image and segmented image.
maskedImage = im;
maskedImage(~BW) = 0;
end
